//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebleToolkit5.ml_resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrebleToolkit5.MultiLang", typeof(MultiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Alcatel 1 (2018).
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: .
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version: 4.7.2.
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Windows Version: 7 / Server 2008 R2 (x64).
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugfixes.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Finished.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 8.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bootloader has been s.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucce.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fully .
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocked..
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ALT+F4 TO CLOSE.
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices.
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of all devices compatible with Treble Toolkit.
        /// </summary>
        public static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ROM.
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: .
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been flashed.
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booted.
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . If your phone bootloops, please try another ROM.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /TWRP image .
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  before requesting a review..
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash GSI.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your phone&apos;s partition style.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please .
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place your ROM in Place_File.
        /// </summary>
        public static string _38 {
            get {
                return ResourceManager.GetString("_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and .
        /// </summary>
        public static string _39 {
            get {
                return ResourceManager.GetString("_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: .
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reboot to the bootloader (must be unlocked) and click &quot;Next&quot;.
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH GSI.
        /// </summary>
        public static string _42 {
            get {
                return ResourceManager.GetString("_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH/BOOT TWRP.
        /// </summary>
        public static string _43 {
            get {
                return ResourceManager.GetString("_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLOCK BOOTLOADER.
        /// </summary>
        public static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH PERMISSIVER.
        /// </summary>
        public static string _45 {
            get {
                return ResourceManager.GetString("_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPATIBLE DEVICES.
        /// </summary>
        public static string _46 {
            get {
                return ResourceManager.GetString("_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - OnePlus 6.
        /// </summary>
        public static string _47 {
            get {
                return ResourceManager.GetString("_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 64GB / 128GB / 256GB.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: 6.28&quot; Optic AMOLED (2280x1080).
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Back) / .
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: 16MP + 20MP (Back) / 16MP (Front).
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10 / 11 (planned).
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version: 4.9.
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: May 22 2018.
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Permissiver.
        /// </summary>
        public static string _55 {
            get {
                return ResourceManager.GetString("_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reboot to TWRP, and select &quot;ADB Sideload&quot; under &quot;Advanced&quot;.
        /// </summary>
        public static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and press Flash.
        /// </summary>
        public static string _57 {
            get {
                return ResourceManager.GetString("_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH.
        /// </summary>
        public static string _58 {
            get {
                return ResourceManager.GetString("_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Sony Xperia 5.
        /// </summary>
        public static string _59 {
            get {
                return ResourceManager.GetString("_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP (Front).
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 128GB.
        /// </summary>
        public static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: 6.1&quot; OLED (2520x1080).
        /// </summary>
        public static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: 12MP / 12MP / 12MP (Back) / 8MP (Front).
        /// </summary>
        public static string _62 {
            get {
                return ResourceManager.GetString("_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10 / 11 (Planned).
        /// </summary>
        public static string _63 {
            get {
                return ResourceManager.GetString("_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: September 24 2019.
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Sony Xperia XZ2.
        /// </summary>
        public static string _65 {
            get {
                return ResourceManager.GetString("_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 64GB.
        /// </summary>
        public static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: .
        /// </summary>
        public static string _67 {
            get {
                return ResourceManager.GetString("_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10.
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8..
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash/Boot TWRP.
        /// </summary>
        public static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please place your TWRP image in .
        /// </summary>
        public static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place_Files_Here/TWRP and select Flash or Boot (depending on your intention.
        /// </summary>
        public static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOT.
        /// </summary>
        public static string _73 {
            get {
                return ResourceManager.GetString("_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWRPBoot.
        /// </summary>
        public static string _74 {
            get {
                return ResourceManager.GetString("_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot TWRP.
        /// </summary>
        public static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you followed the steps on the previous.
        /// </summary>
        public static string _76 {
            get {
                return ResourceManager.GetString("_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window, then press .
        /// </summary>
        public static string _77 {
            get {
                return ResourceManager.GetString("_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        public static string _78 {
            get {
                return ResourceManager.GetString("_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash TWRP.
        /// </summary>
        public static string _79 {
            get {
                return ResourceManager.GetString("_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 (Go Edition).
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you followed the steps on the previous window and make sure your phone&apos;s partition scheme is A.
        /// </summary>
        public static string _80 {
            get {
                return ResourceManager.GetString("_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , then press Flash.
        /// </summary>
        public static string _81 {
            get {
                return ResourceManager.GetString("_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Bootloader.
        /// </summary>
        public static string _82 {
            get {
                return ResourceManager.GetString("_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable OEM Unlocking, and enable USB Debugging and press Unlock..
        /// </summary>
        public static string _83 {
            get {
                return ResourceManager.GetString("_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Your data will be erased.
        /// </summary>
        public static string _84 {
            get {
                return ResourceManager.GetString("_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLOCK.
        /// </summary>
        public static string _85 {
            get {
                return ResourceManager.GetString("_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Portuguese..
        /// </summary>
        public static string _86 {
            get {
                return ResourceManager.GetString("_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Tools: r30.0.5 (November 2020).
        /// </summary>
        public static string _87 {
            get {
                return ResourceManager.GetString("_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version Required: 4.7.2.
        /// </summary>
        public static string _88 {
            get {
                return ResourceManager.GetString("_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Windows Version Required: 7 / Server 2008 R2.
        /// </summary>
        public static string _89 {
            get {
                return ResourceManager.GetString("_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version: 4..
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog: New &quot;Force Reinstall&quot; button in the Launcher (only applicable when updating from Launcher 5.2 or later), fixed dormant adb.exe process, making it impossible to remove Treble Toolkit..
        /// </summary>
        public static string _90 {
            get {
                return ResourceManager.GetString("_90", resourceCulture);
            }
        }
    }
}
