//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebleToolkitUpdaterLauncher.ml_resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrebleToolkitUpdaterLauncher.MultiLang", typeof(MultiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble Toolkit Launcher.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Treble Toolkit Launcher.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download the latest version of Treble Toolkit and launch it automatically..
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCE REINSTALL.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
    }
}
