//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrebleToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrebleToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 (Go Edition).
        /// </summary>
        public static string _1_Go_Edition {
            get {
                return ResourceManager.GetString("_1_Go_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and .
        /// </summary>
        public static string _and {
            get {
                return ResourceManager.GetString("_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and press Flash.
        /// </summary>
        public static string _and_press_Flash {
            get {
                return ResourceManager.GetString("_and_press_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Back) / .
        /// </summary>
        public static string _Back {
            get {
                return ResourceManager.GetString("_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  before requesting a review..
        /// </summary>
        public static string _before_requesting_a_review {
            get {
                return ResourceManager.GetString("_before_requesting_a_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booted.
        /// </summary>
        public static string _booted {
            get {
                return ResourceManager.GetString("_booted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been flashed.
        /// </summary>
        public static string _has_been_flashed {
            get {
                return ResourceManager.GetString("_has_been_flashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . If your phone bootloops, please try another ROM.
        /// </summary>
        public static string _If_your_phone_bootloops_pleas {
            get {
                return ResourceManager.GetString("_If_your_phone_bootloops_pleas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version: 4.7.2.
        /// </summary>
        public static string _NET_Framework_Version_4_7_2 {
            get {
                return ResourceManager.GetString("_NET_Framework_Version_4_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version Required: 4.7.2.
        /// </summary>
        public static string _NET_Framework_Version_Require {
            get {
                return ResourceManager.GetString("_NET_Framework_Version_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string _NEXT {
            get {
                return ResourceManager.GetString("_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , then press Flash.
        /// </summary>
        public static string _then_press_Flash {
            get {
                return ResourceManager.GetString("_then_press_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /TWRP image .
        /// </summary>
        public static string _TWRP_image {
            get {
                return ResourceManager.GetString("_TWRP_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Portuguese..
        /// </summary>
        public static string Added_Portuguese {
            get {
                return ResourceManager.GetString("Added_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8..
        /// </summary>
        public static string Android_Versions_8 {
            get {
                return ResourceManager.GetString("Android_Versions_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10.
        /// </summary>
        public static string Android_Versions_8_1_9_10 {
            get {
                return ResourceManager.GetString("Android_Versions_8_1_9_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10 / 11 (planned).
        /// </summary>
        public static string Android_Versions_8_1_9_10_11_p {
            get {
                return ResourceManager.GetString("Android_Versions_8_1_9_10_11_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Versions: 8.1 / 9 / 10 / 11 (Planned).
        /// </summary>
        public static string Android_Versions_8_1_9_10_11_P0 {
            get {
                return ResourceManager.GetString("Android_Versions_8_1_9_10_11_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOT.
        /// </summary>
        public static string BOOT {
            get {
                return ResourceManager.GetString("BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot TWRP.
        /// </summary>
        public static string Boot_TWRP {
            get {
                return ResourceManager.GetString("Boot_TWRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        public static string Boot0 {
            get {
                return ResourceManager.GetString("Boot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugfixes.
        /// </summary>
        public static string Bugfixes {
            get {
                return ResourceManager.GetString("Bugfixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: .
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: 12MP / 12MP / 12MP (Back) / 8MP (Front).
        /// </summary>
        public static string Cameras_12MP_12MP_12MP_Back_8M {
            get {
                return ResourceManager.GetString("Cameras_12MP_12MP_12MP_Back_8M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: 16MP + 20MP (Back) / 16MP (Front).
        /// </summary>
        public static string Cameras_16MP_20MP_Back_16MP_Fr {
            get {
                return ResourceManager.GetString("Cameras_16MP_20MP_Back_16MP_Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras: .
        /// </summary>
        public static string Cameras0 {
            get {
                return ResourceManager.GetString("Cameras0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog: Update button now opens up the Updater app instead of the website, migratory update to Launcher 5.4 (only applies to Launcher 5.0 and 5.1 users), Launcher now closes after launching Treble Toolkit..
        /// </summary>
        public static string Changelog_Added_Portuguese {
            get {
                return ResourceManager.GetString("Changelog_Added_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices.
        /// </summary>
        public static string Compatible_Devices {
            get {
                return ResourceManager.GetString("Compatible_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Alcatel 1 (2018).
        /// </summary>
        public static string Compatible_Devices_Alcatel_1_2 {
            get {
                return ResourceManager.GetString("Compatible_Devices_Alcatel_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - OnePlus 6.
        /// </summary>
        public static string Compatible_Devices_OnePlus_6 {
            get {
                return ResourceManager.GetString("Compatible_Devices_OnePlus_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Sony Xperia 5.
        /// </summary>
        public static string Compatible_Devices_Sony_Xperia {
            get {
                return ResourceManager.GetString("Compatible_Devices_Sony_Xperia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible Devices - Sony Xperia XZ2.
        /// </summary>
        public static string Compatible_Devices_Sony_Xperia0 {
            get {
                return ResourceManager.GetString("Compatible_Devices_Sony_Xperia0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPATIBLE DEVICES.
        /// </summary>
        public static string COMPATIBLE_DEVICES0 {
            get {
                return ResourceManager.GetString("COMPATIBLE_DEVICES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: .
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: 6.1&quot; OLED (2520x1080).
        /// </summary>
        public static string Display_6_1_OLED_2520x1080 {
            get {
                return ResourceManager.GetString("Display_6_1_OLED_2520x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: 6.28&quot; Optic AMOLED (2280x1080).
        /// </summary>
        public static string Display_6_28_Optic_AMOLED_2280 {
            get {
                return ResourceManager.GetString("Display_6_28_Optic_AMOLED_2280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH.
        /// </summary>
        public static string FLASH {
            get {
                return ResourceManager.GetString("FLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH/BOOT TWRP.
        /// </summary>
        public static string FLASH_BOOT_TWRP {
            get {
                return ResourceManager.GetString("FLASH_BOOT_TWRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash/Boot TWRP.
        /// </summary>
        public static string Flash_Boot_TWRP0 {
            get {
                return ResourceManager.GetString("Flash_Boot_TWRP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash GSI.
        /// </summary>
        public static string Flash_GSI {
            get {
                return ResourceManager.GetString("Flash_GSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH GSI.
        /// </summary>
        public static string FLASH_GSI0 {
            get {
                return ResourceManager.GetString("FLASH_GSI0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASH PERMISSIVER.
        /// </summary>
        public static string FLASH_PERMISSIVER {
            get {
                return ResourceManager.GetString("FLASH_PERMISSIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Permissiver.
        /// </summary>
        public static string Flash_Permissiver0 {
            get {
                return ResourceManager.GetString("Flash_Permissiver0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash TWRP.
        /// </summary>
        public static string Flash_TWRP {
            get {
                return ResourceManager.GetString("Flash_TWRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fully .
        /// </summary>
        public static string fully {
            get {
                return ResourceManager.GetString("fully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version: 4..
        /// </summary>
        public static string Kernel_Version_4 {
            get {
                return ResourceManager.GetString("Kernel_Version_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version: 4.9.
        /// </summary>
        public static string Kernel_Version_4_9 {
            get {
                return ResourceManager.GetString("Kernel_Version_4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        public static string MAIN_MENU {
            get {
                return ResourceManager.GetString("MAIN_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you followed the steps on the previous.
        /// </summary>
        public static string Make_sure_you_followed_the_ste {
            get {
                return ResourceManager.GetString("Make_sure_you_followed_the_ste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you followed the steps on the previous window and make sure your phone&apos;s partition scheme is A.
        /// </summary>
        public static string Make_sure_you_followed_the_ste0 {
            get {
                return ResourceManager.GetString("Make_sure_you_followed_the_ste0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Windows Version Required: 7 / Server 2008 R2.
        /// </summary>
        public static string Minimum_Windows_Version_Requir {
            get {
                return ResourceManager.GetString("Minimum_Windows_Version_Requir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP (Front).
        /// </summary>
        public static string MP_Front {
            get {
                return ResourceManager.GetString("MP_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Your data will be erased.
        /// </summary>
        public static string NOTE_Your_data_will_be_erased {
            get {
                return ResourceManager.GetString("NOTE_Your_data_will_be_erased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnePlus 6.
        /// </summary>
        public static string OnePlus_6 {
            get {
                return ResourceManager.GetString("OnePlus_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place_Files_Here/TWRP and select Flash or Boot (depending on your intention.
        /// </summary>
        public static string Place_Files_Here_TWRP_and_sele {
            get {
                return ResourceManager.GetString("Place_Files_Here_TWRP_and_sele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place your ROM in Place_File.
        /// </summary>
        public static string place_your_ROM_in_Place_File {
            get {
                return ResourceManager.GetString("place_your_ROM_in_Place_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Tools: r30.0.5 (November 2020).
        /// </summary>
        public static string Platform_Tools_r30_0_5_Novembe {
            get {
                return ResourceManager.GetString("Platform_Tools_r30_0_5_Novembe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please .
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable OEM Unlocking, and enable USB Debugging and press Unlock..
        /// </summary>
        public static string Please_enable_OEM_Unlocking_an {
            get {
                return ResourceManager.GetString("Please_enable_OEM_Unlocking_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please place your TWRP image in .
        /// </summary>
        public static string Please_place_your_TWRP_image_i {
            get {
                return ResourceManager.GetString("Please_place_your_TWRP_image_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reboot to TWRP, and select &quot;ADB Sideload&quot; under &quot;Advanced&quot;.
        /// </summary>
        public static string Please_reboot_to_TWRP_and_sele {
            get {
                return ResourceManager.GetString("Please_reboot_to_TWRP_and_sele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your phone&apos;s partition style.
        /// </summary>
        public static string Please_select_your_phone_s_par {
            get {
                return ResourceManager.GetString("Please_select_your_phone_s_par", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ALT+F4 TO CLOSE.
        /// </summary>
        public static string PRESS_ALT_F4_TO_CLOSE {
            get {
                return ResourceManager.GetString("PRESS_ALT_F4_TO_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Finished.
        /// </summary>
        public static string Process_Finished {
            get {
                return ResourceManager.GetString("Process_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reboot to the bootloader (must be unlocked) and click &quot;Next&quot;.
        /// </summary>
        public static string reboot_to_the_bootloader_must_ {
            get {
                return ResourceManager.GetString("reboot_to_the_bootloader_must_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: .
        /// </summary>
        public static string Release_Date {
            get {
                return ResourceManager.GetString("Release_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: May 22 2018.
        /// </summary>
        public static string Release_Date_May_22_2018 {
            get {
                return ResourceManager.GetString("Release_Date_May_22_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: September 24 2019.
        /// </summary>
        public static string Release_Date_September_24_2019 {
            get {
                return ResourceManager.GetString("Release_Date_September_24_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Windows Version: 7 / Server 2008 R2 (x64).
        /// </summary>
        public static string Required_Windows_Version_7_Ser {
            get {
                return ResourceManager.GetString("Required_Windows_Version_7_Ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        public static string ss {
            get {
                return ResourceManager.GetString("ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 128GB.
        /// </summary>
        public static string Storage_128GB {
            get {
                return ResourceManager.GetString("Storage_128GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 64GB.
        /// </summary>
        public static string Storage_64GB {
            get {
                return ResourceManager.GetString("Storage_64GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 64GB / 128GB / 256GB.
        /// </summary>
        public static string Storage_64GB_128GB_256GB {
            get {
                return ResourceManager.GetString("Storage_64GB_128GB_256GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage: 8.
        /// </summary>
        public static string Storage_8 {
            get {
                return ResourceManager.GetString("Storage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of all devices compatible with Treble Toolkit.
        /// </summary>
        public static string This_is_a_list_of_all_devices_ {
            get {
                return ResourceManager.GetString("This_is_a_list_of_all_devices_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWRPBoot.
        /// </summary>
        public static string TWRPBoot {
            get {
                return ResourceManager.GetString("TWRPBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucce.
        /// </summary>
        public static string ucce {
            get {
                return ResourceManager.GetString("ucce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLOCK.
        /// </summary>
        public static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLOCK BOOTLOADER.
        /// </summary>
        public static string UNLOCK_BOOTLOADER {
            get {
                return ResourceManager.GetString("UNLOCK_BOOTLOADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Bootloader.
        /// </summary>
        public static string Unlock_Bootloader0 {
            get {
                return ResourceManager.GetString("Unlock_Bootloader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocked..
        /// </summary>
        public static string unlocked {
            get {
                return ResourceManager.GetString("unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window, then press .
        /// </summary>
        public static string window_then_press {
            get {
                return ResourceManager.GetString("window_then_press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x1080).
        /// </summary>
        public static string x1080 {
            get {
                return ResourceManager.GetString("x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bootloader has been s.
        /// </summary>
        public static string Your_bootloader_has_been_s {
            get {
                return ResourceManager.GetString("Your_bootloader_has_been_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ROM.
        /// </summary>
        public static string Your_ROM {
            get {
                return ResourceManager.GetString("Your_ROM", resourceCulture);
            }
        }
    }
}
